[book]
authors = ["Bli_Aik"]
language = "en"
src = "src"
title = "SoupRune Hekatonhemeron"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
no-section-label = true
